package no.uio.ifi.in2000.team19.prosjekt.model

enum class AdviceCategory {
    COOL,
    COOLOTHER,
    COLD,
    COLDLONGFUR,
    COLDOTHER,
    COLDOTHERLONGFUR,
    FREEZING,
    SALT,
    WARM,
    WARMFLAT,
    VERYWARM,
    VERYWARMFLAT,
    HEATWAVE,
    RAIN,
    THUNDER,
    SNOW,
    SUNBURN,
    TICK,
    VIPER,
    SAFE,
    CAR,
    NEWYEAR
} //HEATWAVEWHITENAKED, //VERYWARMWHITENAKED,